version: "3"

services:
  otel_collector:
    image: docker.io/otel/opentelemetry-collector:latest
    volumes:
      - ./docker/otel_collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    command: ["--config=/etc/otel-collector-config.yaml"]
  mongo:
    image: docker.io/mongo:latest
    ports:
      - "27017:27017"
  application:
    image: python-poetry-empty
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8000:8000"
    command: ["poetry", "run", "fastapi_factory_utilities-example"]
