[_]
schema-version = "0.2"

[project]
id = "info.sysunicorns.fastapi_factory_utilities_example"
version = "0.1.0"

[io.buildpacks]
exclude = [
    ".venv",
    ".devcontainer",
    ".github",
    ".mypy_cache",
    "build",
    ".ruff_cache",
    "docker",
    ".git"
]
