[tool.poetry]
name = "TODO-ADD-MODULE-NAME-HERE"
version = "0.1.0"
description = ""
authors = ["miragecentury <victorien.vanroye@gmail.com>"]
readme = "README.md"
packages = [
    { include = "TODO-ADD-MODULE-NAME-HERE", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.test.dependencies]


[tool.poetry.extras]


[tool.poetry.dev-dependencies]
pytest = "^8.2.0"
pytest-xdist = "^3.6.1"
pytest-cov = "^5.0.0"

[tool.poetry.scripts]
python-stack-example = "TODO-ADD-MODULE-NAME-HERE.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "tests -n auto --color=yes"
filterwarnings = [
]

[tool.black]
line-length = 88
target-version = ['py311']