apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: python_factory_example
build:
  artifacts:
    - image: python_factory_example
      context: .
      runtimeType: python
      buildpacks:
        clearCache: false
        projectDescriptor: project.toml
        trustBuilder: true
        builder: paketobuildpacks/builder-jammy-base
        buildpacks:
          - paketo-buildpacks/python

      # docker:
      #   cacheFrom:
      #     - docker.io/library/python:3.12.4-slim-bullseye
      #   dockerfile: "Dockerfile"
      #   buildArgs:
      #     DEV: "false"
  local:
    push: false
    useBuildkit: true
deploy:
  docker:
    useCompose: false
    images:
      - python_factory_example
portForward:
  - resourceType: container
    resourceName: python_factory_example
    port: 8000
    localPort: 8000
    address: localhost
