apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: fastapi_factory_utilities_example
build:
  artifacts:
    - image: fastapi_factory_utilities_example
      context: .
      runtimeType: python
      buildpacks:
        clearCache: false
        projectDescriptor: project.toml
        trustBuilder: true
        builder: paketobuildpacks/builder-jammy-base
        buildpacks:
          - paketo-buildpacks/python
        dependencies:
          paths:
            - pyproject.toml
            - src/*
      platforms:
        - "linux/amd64"
  local:
    useBuildkit: true

test:
  - image: fastapi_factory_utilities_example
    context: .
    custom:
      - command: "pre-commit run --all-files"
portForward:
  - resourceType: container
    resourceName: fastapi_factory_utilities_example
    port: 8000
    localPort: 8000
    address: localhost
profiles:
  - name: development-in-container
    activation:
      - env: ENVIRONMENT=development
    build:
      local:
        push: false
    deploy:
      docker:
        useCompose: false
        images:
          - fastapi_factory_utilities_example
    test:
      - image: fastapi_factory_utilities_example
        context: .
        custom:
          - command: "pre-commit run --all-files --hook-stage commit"
            dependencies:
              paths:
                - .pre-commit-config.yaml
                - pyproject.toml
                - src/*
                - tests/*
  - name: development-in-cluster
    activation:
      - env: ENVIRONMENT=development
    build:
      local:
        push: false
    deploy:
      docker:
        useCompose: false
        images:
          - fastapi_factory_utilities_example
