---
application:
  service_name: python_factory_example
  service_namespace: python_factory_example
  title: Python Factory Example
  description: An example application for Python Factory
  version: 0.1.0
  environment: ${ENVIRONMENT:development}
  debug: ${APPLICATION_DEBUG:false}
  reload: ${APPLICATION_RELOAD:false}

plugins:
  activate:
    - opentelemetry_plugin
